## Crop Yield Machine Learning

In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Load the dataset

In [61]:
df = pd.read_csv(r"C:\Data Analyst\crop_yield_data.csv")

df.head()

,rainfall_mm,soil_quality_index,farm_size_hectares,sunlight_hours,fertilizer_kg,crop_yield
0,1626,9,636,11,1006,404
1,1959,9,73,11,112,115
2,1360,1,352,5,702,231
3,1794,2,948,7,299,537
4,1630,5,884,5,2733,554

### Checking for Data quality and integrity

In [62]:
# overall quality of data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rainfall_mm         3000 non-null   int64
 1   soil_quality_index  3000 non-null   int64
 2   farm_size_hectares  3000 non-null   int64
 3   sunlight_hours      3000 non-null   int64
 4   fertilizer_kg       3000 non-null   int64
 5   crop_yield          3000 non-null   int64
dtypes: int64(6)
memory usage: 140.8 KB

In [63]:
# Describe the data

df.describe().T

,count,mean,std,min,25%,50%,75%,max
rainfall_mm,3000.0,1263.095000,432.371756,500.0,896.00,1277.0,1636.0,2000.0
soil_quality_index,3000.0,5.506667,2.855172,1.0,3.00,6.0,8.0,10.0
farm_size_hectares,3000.0,498.801000,287.122742,10.0,242.00,505.0,741.0,1000.0
sunlight_hours,3000.0,7.995333,2.621501,4.0,6.00,8.0,10.0,12.0
fertilizer_kg,3000.0,1549.450333,814.326919,100.0,869.75,1542.0,2225.0,3000.0
crop_yield,3000.0,328.099000,145.036503,46.0,199.00,332.0,455.0,628.0

In [64]:
# check for duplicates

df[df.duplicated()]

Empty DataFrame
Columns: [rainfall_mm, soil_quality_index, farm_size_hectares, sunlight_hours, fertilizer_kg, crop_yield]
Index: []

### EDA

In [65]:
# correlation between fertilizer_kg and crop_yield

df.corr(method='spearman')

,rainfall_mm,soil_quality_index,farm_size_hectares,sunlight_hours,fertilizer_kg,crop_yield
rainfall_mm,1.000000,-0.021639,0.000597,-0.005046,-0.030095,0.082942
soil_quality_index,-0.021639,1.000000,0.005605,0.002055,0.007359,0.041956
farm_size_hectares,0.000597,0.005605,1.000000,-0.010055,-0.007162,0.989618
sunlight_hours,-0.005046,0.002055,-0.010055,1.000000,0.015910,-0.006718
fertilizer_kg,-0.030095,0.007359,-0.007162,0.015910,1.000000,0.098454
crop_yield,0.082942,0.041956,0.989618,-0.006718,0.098454,1.000000

#### from the correlation coefficient coefficient, the farm_size-hectares have the highest positive correlation with the crop yield,
#### as the farm size increase, the crop yield increase. the sunlight_hourse is negatively correlated with the crop_yield, the more the sun_light, the less the crop_yield.

In [66]:
corr_cols = ['rainfall_mm', 'soil_quality_index', 'sunlight_hours',	'fertilizer_kg', 'crop_yield']

df[corr_cols]

,rainfall_mm,soil_quality_index,sunlight_hours,fertilizer_kg,crop_yield
0,1626,9,11,1006,404
1,1959,9,11,112,115
2,1360,1,5,702,231
3,1794,2,7,299,537
4,1630,5,5,2733,554
...,...,...,...,...,...
2995,1483,9,12,2739,155
2996,804,9,4,1898,319
2997,870,1,7,2282,129
2998,1352,6,11,2901,493
2999,883,7,11,485,134

In [67]:
df[corr_cols].corr(method='spearman')

,rainfall_mm,soil_quality_index,sunlight_hours,fertilizer_kg,crop_yield
rainfall_mm,1.000000,-0.021639,-0.005046,-0.030095,0.082942
soil_quality_index,-0.021639,1.000000,0.002055,0.007359,0.041956
sunlight_hours,-0.005046,0.002055,1.000000,0.015910,-0.006718
fertilizer_kg,-0.030095,0.007359,0.015910,1.000000,0.098454
crop_yield,0.082942,0.041956,-0.006718,0.098454,1.000000

### Building the Machine Learning Model

In [68]:
# dividing our data into Feature and Target

X= df.drop('crop_yield', axis = 1)
y = df['crop_yield']

### Importing the model

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import  r2_score, mean_squared_error, mean_absolute_error

In [70]:
# train the model

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=42)

In [71]:
# Normalize the data

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [72]:
# initialize the model algorithm

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
lr

LinearRegression()

In [73]:
lr.coef_

array([ 12.88033026,   5.74263454, 142.10555741,   0.24572297,
        16.33627647])

In [74]:
# test the model by predicting

y_pred = lr.predict(X_test_scaled)

y_pred

array([181.1038711 , 308.7240935 , 290.69107064, 172.06104563,
       261.19092548, 416.97995016, 491.14798776, 162.65117411,
       367.64016538, 397.17893957, 356.3341652 , 356.48129781,
       566.41225158, 427.63056945, 402.40878226, 125.73677922,
       545.59132712, 539.91641363, 112.39813143, 529.51410451,
       516.19859676, 356.5918367 , 183.29778958, 163.18420791,
       432.82188309, 327.37376759, 144.97936991, 438.53485309,
       216.14064921, 314.09229843, 396.61358677, 302.37264778,
       514.70291958, 159.59243611, 368.95316171, 149.84979734,
       191.53941274, 196.9842229 , 552.49262721, 380.80093884,
       344.78821218, 256.516345  , 333.15884068, 582.29361561,
       191.65540254, 168.53815268, 301.87216378, 530.67028057,
       109.36383531, 156.20711043, 396.92338355, 406.09119644,
       369.04265172, 186.31143248, 171.43955852, 271.59518833,
       329.63114884, 370.99743286, 196.19433062, 289.34349453,
       361.83973467, 246.49517712, 278.20833745, 367.32608243,
       430.1892542 , 485.79051566, 479.33820952, 176.78251049,
       553.84385005, 172.01826053, 339.2385515 , 122.85428718,
       416.86000056, 320.59814372,  72.47401919,  74.77212691,
       361.406473  , 505.97352516, 125.30458709, 108.44659237,
       211.26289956, 465.1687897 , 396.72746901, 157.64761522,
       556.19436451, 167.42253466, 530.85080011, 465.14909271,
       167.52069519, 462.76001313, 562.64072156, 200.22595626,
       500.9487658 , 462.58291155, 187.91779469, 567.04547519,
       242.16030457, 450.84414594, 121.77593738, 324.9949085 ,
        73.81149375, 373.07047489, 167.05414878, 116.34804637,
       466.4957718 , 560.76173526, 211.85604229, 225.76512157,
       338.50144476, 122.30591641, 150.70859662, 348.04769276,
       468.35476606, 143.21552915, 258.10202736, 308.41235741,
       403.99306525, 121.54170135, 497.96229783, 478.88076877,
       440.82148916, 374.68510032, 177.22290785, 394.04669452,
       241.72909474, 315.29068136, 212.65959607, 277.07487501,
       516.35342096, 105.86715548, 517.50619647, 510.97016934,
       188.7896952 , 465.96695209, 509.232991  , 413.17841558,
       226.33757217, 581.49794934, 256.24816395, 462.92444372,
       494.88881942, 214.59258473, 349.60369829, 141.89419124,
       531.43072343, 135.32952748, 341.20203025, 558.46527594,
       491.2514439 , 165.9687474 , 327.55153509, 419.87227283,
       346.32784463, 561.24416334, 134.49639772, 352.13024779,
       328.91357986, 405.18097045, 396.90336213, 240.07082245,
       232.11718004, 578.66348816, 549.58041922, 478.52022118,
       430.75374772, 177.34156133,  86.52369004, 146.82776175,
       373.78626523, 395.14627567, 521.03983755, 146.7319546 ,
       143.23364508,  95.1908138 , 491.58520222, 424.75497531,
       231.48644974, 542.5177617 , 334.78860772, 496.00904488,
       389.08083234, 353.29611992, 101.53023684, 530.87974959,
        71.42759495, 479.91467007, 387.98063955, 173.60366865,
       516.630104  , 350.67627376, 388.89140842, 114.37465883,
       351.61489169, 236.4110893 , 330.65556708, 360.08194734,
       464.6140956 , 435.11565976, 483.15512897, 344.93540783,
       193.6081932 , 540.13816303, 586.9481649 , 532.32674957,
       241.37459779, 177.24157203, 375.60709392, 242.98595118,
       395.9461483 , 555.23439154, 348.21117891, 215.47387853,
       498.52097082, 130.8504111 , 389.73009842, 179.9637314 ,
       253.83320785, 264.09423493, 258.52809874, 447.28939209,
       249.64620521, 307.65749673, 165.73085093, 520.3320446 ,
       235.32917836, 203.07451264, 269.19935448, 159.25238775,
       248.84077421, 135.01401883, 531.07485642, 189.25572419,
       366.22034372,  86.42922976, 565.51708146, 492.53660343,
       299.68881278, 154.79388029, 210.25245944, 544.36002783,
       597.48881565, 302.22148388, 130.16751378,  96.19583808,
       105.49533007, 224.87650276, 184.69743678, 362.88640192,
       495.19553463, 562.3410561 , 197.88678852, 395.42062386,
       347.40678086, 521.270572  , 115.11608313, 272.48529826,
       274.43650365, 489.44106783, 341.61541231, 341.24418016,
       274.81578973, 379.06520465, 304.1100073 ,  96.7118691 ,
       217.95766319, 589.95411674, 383.73833741, 364.36931233,
       130.07267793, 116.7608898 , 328.99892483,  98.55077491,
       384.42622323, 537.53210157, 144.89673485, 160.81419584,
       542.66206255, 437.15104513, 325.78769912, 404.77409683,
       551.12456987, 596.15317721, 391.16848463, 390.26263062,
       279.96686534, 505.47427536, 312.22040451, 500.2179824 ,
       334.53765534, 343.73936856, 142.97680744, 440.72833098,
       486.04629382, 263.45954504, 199.91135299, 267.91235234,
       220.89702885, 483.42206936, 421.81990541, 499.67276489,
       560.79340378, 268.32373224, 512.9370989 , 473.99729482,
       570.38546504, 375.90598686, 540.29399731, 294.37875102,
        85.02964963, 213.36642906, 573.36364724, 218.13505931,
       479.02789971, 535.29337526, 381.92658659, 293.96714842,
       122.98120459, 265.83731618, 315.68443603, 311.36720742,
       367.99073904, 243.97387742, 122.97356593, 518.92746197,
       411.19185799, 565.06212542, 202.1050403 , 101.34684356,
       235.54613985, 526.45211456,  86.72509439, 403.86031571,
       238.0394327 , 285.42203853, 119.97822749, 269.57086512,
       300.72013163, 401.22099326,  53.3986407 , 380.15602725,
       156.86359435, 507.22974267, 120.50805092, 189.17573638,
       534.80216833, 451.38540476, 412.56448285, 528.04304114,
       306.10026047, 493.85858888, 455.29879119, 362.77333071,
       103.52883503, 355.81679614, 425.36293603, 108.30325463,
       480.60760253, 206.7195563 , 248.67543311, 194.26851106,
       385.62547969, 117.90605141, 364.95084404, 524.43076761,
       353.07366136, 509.68430263, 193.88760481,  55.86219273,
       456.14930155, 109.77764942, 311.61377456, 359.77040712,
       334.81280348, 341.90553651, 173.62446843, 537.70778563,
       193.26245888,  73.17496205, 541.78345673,  99.118028  ,
       504.05375106, 136.65342723, 175.25065694, 136.52874982,
       237.12622301, 387.95744659, 524.377112  , 484.14615371,
       302.19169857, 253.55713979, 407.66609548, 461.77518874,
       212.92160937, 402.24597747, 526.09171783, 232.49115894,
       349.48029349, 317.96679778, 299.73285333, 319.01777878,
       323.04831159, 290.52814468,  93.11289368, 175.95786669,
       215.85308504, 137.61521396, 103.23448523, 216.85113562,
       131.0787916 , 564.05495412, 336.46067334, 199.12179758,
       285.54326941, 392.00639932, 228.46724723, 216.6834827 ,
       458.47537644, 585.13015448, 111.60218224, 261.17019255,
       475.33052299, 543.09719287, 588.06462997, 448.91679453,
       339.95161849, 381.33232969, 406.24359238, 400.90843226,
       197.00529715, 176.18042159, 362.6025875 , 544.81313869,
       239.25748071, 590.11068681, 401.65883423, 497.86737503,
       361.55809972, 257.5050159 , 317.29303937, 503.52673608,
       602.45411523, 127.06800069, 396.0285794 , 314.280986  ,
       459.95254299, 293.10038416, 400.63256617, 281.80669049,
        61.20630103, 203.75013443, 271.38601322,  81.76290815,
       526.4871312 , 393.11338662, 553.02169142, 406.55913738,
       182.61292685, 165.71368353, 453.55172088, 148.9603551 ,
       223.09129088, 277.81192394, 113.38902278, 123.01724413,
       493.1819307 ,  98.37373683, 243.53085856, 306.2148215 ,
       419.42595869, 365.99946274, 392.50693255, 145.04376296,
       136.77820893, 533.3384861 , 224.49717754, 543.42172348,
       403.40521751, 488.86678726, 238.00156009, 343.0217885 ,
       119.37726246, 309.57174432, 581.04722465, 320.53198045,
       200.83459333, 242.68986004, 256.69329912,  88.11683981,
       206.39712749, 394.17587573, 285.02128302, 493.31948216,
       568.82405888, 399.20508378, 157.76861069, 258.81437363,
       347.23150569, 123.00528607, 144.68118219, 189.09705312,
        70.5527908 , 394.51829516, 151.93724605, 470.75716155,
       214.33375548, 512.01640224, 321.89175829, 351.99563993,
       155.48951794, 154.28603065, 565.40550619,  91.08401731,
       473.16189466, 380.84570734, 248.53509061, 216.60000336,
       190.93920345, 406.97073849, 372.90727296, 492.01647615,
       193.68455864, 480.39502504, 459.91156999, 170.61171832,
       165.87464142, 449.55913125, 134.28647146, 106.48557505,
       456.89627025, 482.04839395, 418.91807817, 266.98004669,
       240.0342228 , 465.06483394, 354.87368718, 404.59841703,
       548.04631485, 484.3441376 , 358.8699178 , 215.69710947,
       199.30551142, 198.2149026 , 193.34721173, 214.61694059,
       447.86224995, 559.93655716, 189.83008802, 280.02245819,
       101.01889793, 534.76071966, 151.61864377, 522.85340104,
       193.21122028, 477.51473467, 208.04092999, 150.01804848,
       299.41900659, 487.65333809, 404.97893756, 314.50596946,
       428.50480013, 432.53249826, 550.33374251, 501.12156016,
       440.43721666, 337.42958849, 257.88084227, 356.62418577,
       209.68915038, 337.74606842, 235.4354277 , 157.55122888,
       433.39368802, 578.03259594, 359.5650625 , 444.92930254,
       118.17541847, 165.48638659, 541.06323791, 448.59813897,
       165.88931191, 395.81734855, 539.90844227, 507.82747285,
       527.88043394, 352.4085292 , 505.80650058, 104.69672514,
       530.74689188, 334.64891367, 225.84757008, 175.18359455,
       227.75826435, 366.48309943, 488.01519951, 191.16895987,
       398.19751875, 300.58305456, 256.55453226, 516.44414292,
       562.81135646, 396.54604913, 402.34719927, 203.91838776,
       492.08823032, 156.35665723, 134.78371905, 445.78136853,
       170.20433269, 400.41456032, 439.3968182 , 533.57442233,
       449.58385001, 463.69450375, 173.44311993, 211.11861644,
        92.28967724, 483.79285173, 173.96292732, 266.97395366,
       470.72694991,  74.37107158, 296.21856084, 480.81980883,
       385.98117766, 278.463543  , 257.77403955, 106.58469965,
       108.50007575, 524.33915679, 459.20809107, 372.4881882 ,
       236.5432346 , 327.88157325,  81.0913739 , 421.8029856 ,
       320.97855915, 501.41227401, 536.39994461, 511.32248373,
       425.87461601, 119.32865939, 293.33569762, 280.78505611,
       350.05358408, 366.16148291, 320.36552187, 198.49997985,
       144.62566617, 518.48816224, 447.89022506, 138.99121105,
       105.23496693, 307.52288357, 519.89661111, 329.88941744,
       122.21419163, 529.75603862, 530.63495011, 264.01501609,
       534.52191175, 420.27714634, 357.73667866,  51.93267597,
       165.37101327, 133.44659368, 502.9786022 , 251.58717211,
       171.29533085, 143.33705713, 351.01600655, 381.60722415,
       264.84961992, 273.3963799 , 457.03011852, 275.74936477,
       152.65592602, 343.75418186, 433.42775504,  80.73772237,
       320.35859381, 581.84912955, 366.70402754,  93.42639307,
       596.4590288 , 353.86758165, 322.8259849 , 529.37121215,
       476.51291099, 567.28004514, 119.07528254, 309.69706294,
       380.68662031, 200.96946914, 489.4896014 , 227.39001445,
       192.21512695, 357.84908681, 340.99226098, 215.91504932,
       575.76868214, 298.58241077, 541.10437044, 147.82870656,
       569.15246718, 296.12499909, 484.15234085, 372.49356678,
       290.02852903, 411.91783531, 532.30330134, 377.24999055,
       422.07889956, 415.66741664, 111.74030632, 490.40139683,
       243.97837833, 535.25151046, 173.17538352, 201.20262876,
       226.86891042, 530.40008482, 368.56247106, 375.22199607,
       191.68541427, 273.91935239, 195.55219162, 368.14425321,
       355.0973924 , 423.73609056, 181.75266552, 157.63931569,
       476.62946997, 428.70047304, 556.39593943, 501.84346301,
       531.02915903, 575.74809109, 164.05672303, 561.45897446,
        81.8240693 , 544.30712684, 538.40406563, 484.73431199,
       123.0649367 , 112.72331404, 372.83213907, 152.89080474,
       217.71272399, 351.20047562, 154.69008892,  89.5192512 ,
       559.54437837, 160.98834827, 359.09415629, 356.74725238,
       288.15675601, 375.46079448, 149.25812026, 341.53582887,
       220.5351084 , 452.3455024 , 564.08470414, 508.67961294,
       471.72918644, 504.66719248,  76.77135276, 321.15128305,
       501.21559598, 199.69943227, 360.78363463, 587.26514925,
       124.67858663, 355.87482628, 268.59659215, 298.57942454,
       497.1776359 , 113.1281792 , 147.57203285, 197.1284562 ,
       333.64213759, 531.95037735, 402.47950547, 227.68022996,
       185.21665538, 481.70413223,  86.32690464, 115.9846208 ,
       197.20463913, 513.66906087, 353.77980532, 159.34611873,
       180.37550094, 116.43275656, 543.93282132, 266.81129849,
       329.49188184, 502.98219932, 155.46582262, 291.56557153,
       164.51788713, 530.57506649, 385.42257079, 554.94955344,
       302.89355907, 349.33480618, 367.05205697, 180.90221061,
       420.10977964, 154.25496313, 582.74793389, 561.43910178,
       374.8999373 , 540.53809894, 162.76585233, 464.36215557,
       398.08798413, 384.08428454, 555.50792502,  49.52554331,
        99.59528575, 119.55142317, 399.82731208, 115.96519778,
       104.71625509, 448.18722984, 328.57607864, 447.64790292,
       496.41016598, 384.50810716, 352.8424938 ,  46.19203902,
       513.4013145 , 361.11590675, 305.83494022, 342.47731006,
       460.66538135, 202.24456519, 508.39312192, 196.99950892,
       521.58110406, 424.05434927,  95.15031658, 231.63558419,
       304.8723676 , 317.89296663, 122.98421549, 254.95954414,
       148.9794187 , 254.52231649, 513.64268301, 446.55220584,
       338.59343361, 121.69751007, 354.93895515, 410.63823006,
       325.82515926, 407.74341503, 572.74575506, 255.32315383,
       482.39508677, 181.19172416, 368.68987915, 208.10755928,
        97.09862324, 523.43927296, 365.30946671, 120.63029394,
       527.66500808, 328.79816332,  58.85587022, 548.01547873,
       419.96333311, 492.37515977, 509.16328021, 219.65426217,
       131.06693422, 535.43138478, 281.23251524, 547.77947501,
       281.37280198, 525.40831322, 252.55748828, 156.7757457 ,
       246.43753309, 186.84415746, 561.68174742, 305.78869366,
       335.1956789 , 254.97794715, 252.91444336, 455.79200669,
       400.70216429, 548.84088487, 268.01077352, 135.47128019,
       372.44946698, 243.69655114, 464.87367709, 331.83742267])

In [75]:
# coefficient of determination

R2 = r2_score(y_test, y_pred)

R2

0.9999961718821034

In [76]:
# Accuracy Score
print('R Square:', R2)
print('Mean Square Error:', mean_squared_error(y_test, y_pred))
print('Mean Absolute Error:',mean_absolute_error(y_test, y_pred))

R Square: 0.9999961718821034
Mean Square Error: 0.08369552186544471
Mean Absolute Error: 0.24850559789380638

## Final Result

### 1 The farm_size determines the crop_yield as evident in the correlation, Spearman's correlation of 0.99, other factors like fertilizer, sunlight duration, rainfall, and soil_quality have little effect on the crop yield.

### 2 The model is perfect as shown by the R squared of 0.99 which shows the model is able to explain 99% of variation in crop yield, MSE of 0.08 explain the model error is minimal and MAE of 0.24 explain the model predictions are off by about 0.24 units.